apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo-deployment
spec:
  selector:
    matchLabels:
      app: app-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
        - name: app-demo-deployment
          image: gcr.io/double-aleph-348710/app-demo:v1
          ports:
            - containerPort: 8080

          

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: app-demo-service
spec:
  selector:
    app: app-demo
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer # type of the service.

